"""Native tool-calling emission — the harness's own tool format over bash.

By default compiled agents invoke ScriptTools via bash
(`python scripts/<tool>.py --command ... --field value`). Every harness
that HAS a native custom-tool mechanism can do better — the model calls
the tool through the harness's structured tool-calling path, and a thin
deterministic shim bridges to the same Python script:

- **opencode** — native custom tools are TypeScript files in
  `.opencode/tool/<name>.ts` (`@opencode-ai/plugin`). We emit one shim
  per json-format tool: zod args derived from the ScriptTool's Pydantic
  Input schema, `execute()` spawning `python3 scripts/<tool>.py --json`
  with the args as JSON on stdin (the `--json` stdin mode ScriptTool.run
  already supports). Deterministic: no logic in TS beyond arg passing.
- **claude / codex** — neither has a per-tool native file format; their
  native route is an **MCP server**. We emit `scripts/mcp_tools_server.py`
  (a FastMCP stdio server that discovers the ScriptTool subclasses in
  `scripts/` at startup and registers each with its real Pydantic input
  model) and the registration: `.mcp.json` for Claude Code, an
  `[mcp_servers.oac-tools]` block appended to each compiled agent TOML
  for Codex.
- **pi** — native tools come from pi's extension API: a TypeScript file
  in `.pi/extensions/` calling `pi.registerTool()` with a Typebox
  parameter schema. We emit one `oac-tools.ts` extension registering
  every json-format tool, each `execute()` bridging to the same
  `python3 scripts/<tool>.py --json` stdin contract. Run pi with
  `--approve` (or trust the project) so the local extension loads.

Enabled with `CompileScript(native_tools=True)` / `oac compile
--native-tools`. Bash invocation docs remain in the prompt either way —
models can fall back when a runtime lacks the shim's runtime (node, mcp).
"""

from __future__ import annotations

import json
from pathlib import Path

from open_agent_compiler.compiler.dialects.opencode.tool_schema import derive_json_schema
from open_agent_compiler.model.core.agent_model import AgentVariant
from open_agent_compiler.model.core.tools_model import ToolDefinition


def collect_json_tools(
    resolved_variants: dict[str, AgentVariant],
) -> list[ToolDefinition]:
    """Every distinct tool (by name) carrying a json_tool contract."""
    found: dict[str, ToolDefinition] = {}
    for agent in resolved_variants.values():
        defn = agent.agent_definition
        tools = list(defn.extra_tools)
        for skill in defn.skills:
            for step in skill.workflow_steps:
                tools.extend(step.tools_used)
        for tool in tools:
            if tool.json_tool is not None:
                found.setdefault(tool.header.name, tool)
    return list(found.values())


def _script_rel_path(tool: ToolDefinition) -> str | None:
    """The build-tree-relative script path the shim shells out to."""
    if not tool.json_tool or not tool.json_tool.tool_scripts:
        return None
    for tool_script in tool.json_tool.tool_scripts:
        for script in tool_script.scripts or []:
            if script.target_file_path:
                return str(script.target_file_path)
    return None


# ---- opencode: .opencode/tool/<name>.ts shims --------------------------

_ZOD_SCALARS = {
    "string": "tool.schema.string()",
    "number": "tool.schema.number()",
    "integer": "tool.schema.number().int()",
    "boolean": "tool.schema.boolean()",
}


def _zod_for_property(prop: dict, required: bool) -> str:
    if isinstance(prop.get("enum"), list) and all(
        isinstance(v, str) for v in prop["enum"]
    ):
        expr = "tool.schema.enum(" + json.dumps(prop["enum"]) + ")"
    else:
        expr = _ZOD_SCALARS.get(str(prop.get("type")), "tool.schema.any()")
    desc = prop.get("description")
    if isinstance(desc, str) and desc:
        expr += f".describe({json.dumps(desc)})"
    if not required:
        expr += ".optional()"
    return expr


def zod_args_from_schema(schema: dict | None) -> str:
    """Render a zod args object body from a JSON schema's top level.

    Nested objects/arrays map to `any()` — the Python side re-validates
    with the real Pydantic model, so the TS layer only needs to be
    permissive-but-typed, never authoritative.
    """
    if not schema or not isinstance(schema.get("properties"), dict):
        return "{}"
    required = set(schema.get("required") or [])
    lines = ["{"]
    for name, prop in schema["properties"].items():
        if not isinstance(prop, dict):
            prop = {}
        lines.append(
            f"    {json.dumps(name)}: {_zod_for_property(prop, name in required)},"
        )
    lines.append("  }")
    return "\n".join(lines)


_TS_SHIM_TEMPLATE = """\
// AUTO-GENERATED by open-agent-compiler (native_tools) — do not edit.
// Native opencode custom tool bridging deterministically to the Python
// ScriptTool: args are validated again by the Pydantic Input model.
import {{ tool }} from "@opencode-ai/plugin"
import {{ spawnSync }} from "node:child_process"

export default tool({{
  description: {description},
  args: {args},
  async execute(args) {{
    const proc = spawnSync("python3", [{script}, "--json"], {{
      input: JSON.stringify(args ?? {{}}),
      encoding: "utf-8",
    }})
    if (proc.error) throw proc.error
    if (proc.status !== 0) {{
      throw new Error(proc.stderr?.trim() || `exit ${{proc.status}}`)
    }}
    return (proc.stdout ?? "").trim()
  }},
}})
"""


def emit_opencode_ts_shims(
    target: Path, resolved_variants: dict[str, AgentVariant],
) -> list[Path]:
    """Write `.opencode/tool/<name>.ts` for every json-contract tool.

    Tools without a resolvable backing script are skipped (their bash
    documentation in the prompt still stands). Returns paths written.
    """
    written: list[Path] = []
    tools = collect_json_tools(resolved_variants)
    if not tools:
        return written
    tool_dir = target / ".opencode" / "tool"
    for tool in tools:
        script_rel = _script_rel_path(tool)
        if script_rel is None:
            continue
        schema = derive_json_schema(tool)
        content = _TS_SHIM_TEMPLATE.format(
            description=json.dumps(tool.header.description or tool.header.name),
            args=zod_args_from_schema(schema),
            script=json.dumps(script_rel),
        )
        tool_dir.mkdir(parents=True, exist_ok=True)
        path = tool_dir / f"{tool.header.name}.ts"
        path.write_text(content)
        written.append(path)
    return written


# ---- pi: .pi/extensions/oac-tools.ts (registerTool) --------------------

_TYPEBOX_SCALARS = {
    "string": "Type.String({opts})",
    "number": "Type.Number({opts})",
    "integer": "Type.Integer({opts})",
    "boolean": "Type.Boolean({opts})",
}


def _typebox_for_property(prop: dict, required: bool) -> str:
    desc = prop.get("description")
    opts = json.dumps({"description": desc}) if isinstance(desc, str) and desc else ""
    if isinstance(prop.get("enum"), list) and all(
        isinstance(v, str) for v in prop["enum"]
    ):
        literals = ", ".join(
            f"Type.Literal({json.dumps(v)})" for v in prop["enum"]
        )
        expr = f"Type.Union([{literals}]{', ' + opts if opts else ''})"
    else:
        template = _TYPEBOX_SCALARS.get(str(prop.get("type")))
        expr = (template.format(opts=opts) if template
                else f"Type.Any({opts})")
    if not required:
        expr = f"Type.Optional({expr})"
    return expr


def typebox_params_from_schema(schema: dict | None) -> str:
    """Render a `Type.Object({...})` body from a JSON schema's top level.

    Same permissive-but-typed stance as the zod mapping: the Python side
    re-validates with the real Pydantic model.
    """
    if not schema or not isinstance(schema.get("properties"), dict):
        return "Type.Object({})"
    required = set(schema.get("required") or [])
    lines = ["Type.Object({"]
    for name, prop in schema["properties"].items():
        if not isinstance(prop, dict):
            prop = {}
        lines.append(
            f"      {json.dumps(name)}: "
            f"{_typebox_for_property(prop, name in required)},"
        )
    lines.append("    })")
    return "\n".join(lines)


_PI_EXTENSION_HEADER = """\
// AUTO-GENERATED by open-agent-compiler (native_tools) — do not edit.
// Native pi extension tools bridging deterministically to the Python
// ScriptTools in scripts/: args are validated again by each tool's
// Pydantic Input model. Loads from .pi/extensions/ when the project is
// trusted (run pi with --approve, or approve the trust prompt).
import type {{ ExtensionAPI }} from "@earendil-works/pi-coding-agent";
import {{ Type }} from "typebox";
import {{ spawnSync }} from "node:child_process";

function runScript(script: string, args: unknown): string {{
  const proc = spawnSync("python3", [script, "--json"], {{
    input: JSON.stringify(args ?? {{}}),
    encoding: "utf-8",
  }});
  if (proc.error) throw proc.error;
  if (proc.status !== 0) {{
    throw new Error(proc.stderr?.trim() || `exit ${{proc.status}}`);
  }}
  return (proc.stdout ?? "").trim();
}}

export default function (pi: ExtensionAPI) {{
{registrations}
}}
"""

_PI_TOOL_REGISTRATION = """\
  pi.registerTool({{
    name: {name},
    label: {label},
    description: {description},
    parameters: {parameters},
    async execute(_toolCallId, params) {{
      return {{
        content: [{{ type: "text", text: runScript({script}, params) }}],
        details: {{}},
      }};
    }},
  }});
"""


def emit_pi_tool_extension(
    target: Path, resolved_variants: dict[str, AgentVariant],
) -> Path | None:
    """Write `.pi/extensions/oac-tools.ts` registering every json tool.

    Returns the path, or None when no tool has both a json contract and
    a resolvable backing script.
    """
    registrations: list[str] = []
    for tool in collect_json_tools(resolved_variants):
        script_rel = _script_rel_path(tool)
        if script_rel is None:
            continue
        registrations.append(_PI_TOOL_REGISTRATION.format(
            name=json.dumps(tool.header.name),
            label=json.dumps(tool.header.name.replace("-", " ").title()),
            description=json.dumps(
                tool.header.description or tool.header.name),
            parameters=typebox_params_from_schema(derive_json_schema(tool)),
            script=json.dumps(script_rel),
        ))
    if not registrations:
        return None
    ext_dir = target / ".pi" / "extensions"
    ext_dir.mkdir(parents=True, exist_ok=True)
    path = ext_dir / "oac-tools.ts"
    path.write_text(_PI_EXTENSION_HEADER.format(
        registrations="\n".join(registrations).rstrip(),
    ))
    return path


# ---- claude / codex: MCP tools server ---------------------------------

_MCP_SERVER_TEMPLATE = '''\
"""AUTO-GENERATED by open-agent-compiler (native_tools) — do not edit.

Stdio MCP server exposing this build's ScriptTools natively. At startup
it imports every Python file in scripts/, finds ScriptTool subclasses,
and registers one MCP tool per class using its real Pydantic Input
model — so MCP-aware harnesses (Claude Code, Codex, pi via ext:mcp)
call the same tools the bash path documents.

Run: python3 scripts/mcp_tools_server.py   (needs: pip install mcp)
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

from mcp.server.fastmcp import FastMCP

from open_agent_compiler.runtime import ScriptTool

SCRIPTS_DIR = Path(__file__).resolve().parent

mcp = FastMCP("oac-tools")


def _tool_classes():
    seen: set[str] = set()
    for py in sorted(SCRIPTS_DIR.glob("*.py")):
        if py.name == Path(__file__).name:
            continue
        spec = importlib.util.spec_from_file_location(f"_oac_tool_{py.stem}", py)
        if spec is None or spec.loader is None:
            continue
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        try:
            spec.loader.exec_module(module)
        except Exception as exc:  # a broken script must not sink the server
            print(f"[oac-tools] skipping {py.name}: {exc}", file=sys.stderr)
            continue
        for attr in vars(module).values():
            if (
                isinstance(attr, type)
                and issubclass(attr, ScriptTool)
                and attr is not ScriptTool
                and getattr(attr, "name", None)
                and attr.name not in seen
            ):
                seen.add(attr.name)
                yield attr


def _register(cls) -> None:
    input_model = cls._get_input_type()

    def handler(**kwargs):
        validated = input_model.model_validate(kwargs)
        result = cls().execute(validated)
        return result.model_dump()

    handler.__name__ = cls.name
    handler.__doc__ = cls.description
    # Give FastMCP the real input schema via the Pydantic model signature.
    import inspect

    params = [
        inspect.Parameter(
            field, inspect.Parameter.KEYWORD_ONLY,
            default=(info.default if not info.is_required() else inspect.Parameter.empty),
            annotation=info.annotation,
        )
        for field, info in input_model.model_fields.items()
    ]
    handler.__signature__ = inspect.Signature(params)
    mcp.tool(name=cls.name, description=cls.description)(handler)


for _cls in _tool_classes():
    _register(_cls)


if __name__ == "__main__":
    mcp.run()
'''


def emit_mcp_tools_server(target: Path) -> Path:
    scripts_dir = target / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    path = scripts_dir / "mcp_tools_server.py"
    path.write_text(_MCP_SERVER_TEMPLATE)
    return path


def emit_claude_mcp_config(target: Path) -> Path:
    """Write/merge `.mcp.json` registering the oac-tools stdio server —
    Claude Code's native route to custom tools."""
    path = target / ".mcp.json"
    config: dict = {}
    if path.exists():
        try:
            config = json.loads(path.read_text())
        except json.JSONDecodeError:
            config = {}
    servers = config.setdefault("mcpServers", {})
    servers["oac-tools"] = {
        "command": "python3",
        "args": ["scripts/mcp_tools_server.py"],
    }
    path.write_text(json.dumps(config, indent=2) + "\n")
    return path


_CODEX_MCP_BLOCK = """
[mcp_servers.oac-tools]
command = "python3"
args = ["scripts/mcp_tools_server.py"]
"""


def append_codex_mcp_server(target: Path) -> list[Path]:
    """Append the oac-tools stdio server to each compiled codex agent TOML —
    Codex's native route to custom tools."""
    agents_dir = target / ".codex" / "agents"
    touched: list[Path] = []
    if not agents_dir.exists():
        return touched
    for toml_path in sorted(agents_dir.glob("*.toml")):
        content = toml_path.read_text()
        if "[mcp_servers.oac-tools]" in content:
            continue
        toml_path.write_text(content.rstrip("\n") + "\n" + _CODEX_MCP_BLOCK)
        touched.append(toml_path)
    return touched
