"""Public API for open-agent-compiler.

Both internal callers and consumers reach the public surface as
`from open_agent_compiler import AgentRegistry, build, ScriptTool, ...` —
every name listed in __all__ is part of the stable contract.
"""

from __future__ import annotations

from open_agent_compiler.compiler.compile import build, build_variant
from open_agent_compiler.compiler.core.compiler import Compiler
from open_agent_compiler.compiler.dialects.opencode.compiler import OpenCodeCompiler
from open_agent_compiler.compiler.reader import (
    CompiledAgent,
    load_compiled_agent,
    parse_compiled_agent,
)
from open_agent_compiler.compiler.script import CompileScript
from open_agent_compiler.interactive import (
    CallbackSink,
    CollectingSink,
    Event,
    EventEmitter,
    EventKind,
    EventSink,
    InteractiveAgentSpec,
    NullSink,
    QueueSink,
    ToolSpec,
    as_sink,
    build_interactive_spec,
    invoke_runner,
    render_interactive_prompt,
    runner_accepts_emitter,
)
from open_agent_compiler.improvement import (
    ComponentRegistry,
    ComponentVersion,
    IdentityMutator,
    IterativeLoop,
    LLMPromptRewriter,
    MutationContext,
    Mutator,
    OptimisationCriterion,
    PromptPrefixMutator,
    PromptSuffixMutator,
    TemperatureMutator,
    FleetResult,
    ImprovementUnit,
    UnitOutcome,
    agent_unit,
    branch_component_id,
    branch_unit,
    build_branch_evaluator,
    build_branch_loop,
    build_outcome_branch_evaluator,
    build_outcome_branch_loop,
    make_branch_outcome_judge_test,
    run_fleet,
    OpencodeRunner,
    OpencodeMutatorClient,
    flat_candidate_from_project_root,
    ContractPredicate,
    ContractResult,
    RunOutcome,
    all_of,
    contract_gate,
    require_any_tool_called,
    require_artifact,
    require_outcome,
    require_subagent_dispatched,
    require_tool_called,
)
# Improvement.Criterion exists too but conflicts with workflow's Criterion;
# import directly: `from open_agent_compiler.improvement import Criterion as OptCriterion`.
from open_agent_compiler.model.core.agent_model import (
    AgentDefinition,
    AgentHeader,
    AgentMode,
    AgentVariant,
    AgentWorkflowStep,
    CompilationConfig,
    MCPServerDefinition,
    ModelParameters,
    TemplateSlot,
    TemplateTree,
    TodoMode,
    ToolFormat,
    ToolPermissions as AgentToolPermissions,
)
from open_agent_compiler.model.core.access_profile import (
    AccessProfile,
    AccessProfileRegistry,
    ResourceBinding,
    ResourceKind,
)
from open_agent_compiler.model.core.capability_bundle import (
    ClientCapabilityBundle,
    ClientDatasource,
    ClientMCPServer,
    CollisionPolicy,
    MCPTransport,
    MergedCapabilitySurface,
    merge_capabilities,
)
from open_agent_compiler.model.core.context_blocks import (
    ContextBlock,
    PromptAssembler,
    Volatility,
    volatility_rank,
)
from open_agent_compiler.datasource import (
    DatasourceAdapter,
    DatasourceItem,
    DatasourceKind,
    DatasourceProfile,
    DatasourceStructure,
    DerivedToolSpec,
    MCPDatasourceAdapter,
    MCPEnumerator,
    NamingConvention,
    ResourceBindingAdapter,
    ResourceBindingEnumerator,
    ToolInputSchema,
    apply_profile_to_datasource,
    derive_datasource_tools,
    profile_datasource,
)
from open_agent_compiler.personalization import (
    ClientOverlay,
    ClientSpec,
    ExampleTask,
    PersonalizationRun,
    PersonalizationRunResult,
    PersonalizedCompile,
    SpecElicitationError,
    build_client_criterion,
    build_client_judge_test,
    build_client_prompt_block,
    build_client_rubric,
    build_joint_mutators,
    build_personalized_opencode_json,
    build_session_judge_evaluator,
    compile_personalized,
    elicit_client_spec,
    example_task_probe_key,
    make_spec_probe_synthesizer,
    overlay_variant,
    parse_client_spec,
    seed_probes_from_spec,
    spec_probe_keys,
    write_personalized_opencode_json,
)
from open_agent_compiler.model.core.task_model import TaskHandle, TaskKind, TaskStatus
from open_agent_compiler.model.core.agent_registry import AgentRegistry
from open_agent_compiler.model.core.core_tools_model import (
    OpencodeManagerAction,
    create_opencode_manager_tool,
)
from open_agent_compiler.model.core.mock_model import (
    MockKind,
    MockProfile,
    MockResponse,
    MockState,
)
from open_agent_compiler.model.core.test_model import (
    AgentTest,
    AnyEvaluator,
    CapabilityTest,
    EqualsEvaluator,
    Evaluator,
    EvaluatorKind,
    JsonPathEvaluator,
    LLMJudgeEvaluator,
    PathOrderEvaluator,
    PermissionAbsentEvaluator,
    PermissionPresentEvaluator,
    RegexEvaluator,
    FactRecallEvaluator,
    FactSpec,
    SubstringEvaluator,
    ToolCalledEvaluator,
    ToolNotCalledEvaluator,
    ToolTest,
    Turn,
)
from open_agent_compiler.model.core.branch_model import BranchTest, StepContract
from open_agent_compiler.testing.probe_pack import (
    PackProbe,
    ProbePack,
    load_pack,
    pack_to_tests,
)
from open_agent_compiler.testing.branch import (
    BranchInvoker,
    BranchRunResult,
    BranchTrajectory,
    evaluate_step_contracts,
    mock_chain_invoker,
    run_branch_test,
    scripted_invoker,
)
from open_agent_compiler.testing.provider_guard import (
    assert_no_raw_provider_endpoints,
    scan_repo as scan_repo_for_raw_provider_endpoints,
)
from open_agent_compiler.model.core.model_preset import (
    ModelLimits,
    ModelPreset,
    ReasoningField,
    SamplingDefaults,
)
from open_agent_compiler.model.core.compilation_context import (
    CompilationContext,
    active as active_compilation_context,
    current_context,
)
from open_agent_compiler.model.core.split_profile import SplitProfile
from open_agent_compiler.model.core.variant_spec import VariantSpec, apply_variant
from open_agent_compiler.model.core.permissions_model import (
    BashToolPermission,
    DefaultTools,
    JsonToolPermission,
    Permission,
    PermissionType,
    ToolPermission,
    ToolScope,
)
from open_agent_compiler.model.core.skills_model import (
    SkillDefinition,
    SkillExample,
    WorkflowStep,
)
from open_agent_compiler.model.core.workflow_model import (
    Criterion,
    Gate,
    GateCheck,
    GateLogic,
    Route,
    ToolUse,
    WorkflowStepDefinition,
)
from open_agent_compiler.model.core.tools_model import (
    ScriptDefinition,
    SupportedScriptTypes,
    ToolDefinition,
    ToolDefinitionHeader,
    ToolDefinitionLogicBash,
    ToolDefinitionLogicJson,
    ToolScriptDefinition,
)
from open_agent_compiler.runtime import ResourceHandle, ScriptTool, StreamFormat
from open_agent_compiler.runtime_spawn import (
    SpawnAgentInput,
    SpawnAgentOutput,
    SpawnAgentTool,
)

__all__ = [
    # Compiler entry points
    "build",
    "build_variant",
    "Compiler",
    "CompileScript",
    "OpenCodeCompiler",
    "VariantSpec",
    "SplitProfile",
    "apply_variant",
    # interactive target + artifact reader
    "InteractiveAgentSpec",
    "ToolSpec",
    "build_interactive_spec",
    "render_interactive_prompt",
    # interactive event sink / emitter
    "Event",
    "EventKind",
    "EventSink",
    "NullSink",
    "CallbackSink",
    "CollectingSink",
    "QueueSink",
    "as_sink",
    "EventEmitter",
    "runner_accepts_emitter",
    "invoke_runner",
    "CompiledAgent",
    "load_compiled_agent",
    "parse_compiled_agent",
    "CompilationContext",
    "active_compilation_context",
    "current_context",
    # Agent model
    "AgentDefinition",
    "AgentHeader",
    "AgentMode",
    "AgentVariant",
    "AgentWorkflowStep",
    "CompilationConfig",
    "ModelParameters",
    "TemplateSlot",
    "TemplateTree",
    "TodoMode",
    "ToolFormat",
    "AgentToolPermissions",
    "MCPServerDefinition",
    "AgentRegistry",
    # Access profiles (resource routing)
    "AccessProfile",
    "AccessProfileRegistry",
    "ResourceBinding",
    "ResourceKind",
    # Per-client capability merge (Phase B)
    "ClientCapabilityBundle",
    "ClientMCPServer",
    "ClientDatasource",
    "MergedCapabilitySurface",
    "merge_capabilities",
    "CollisionPolicy",
    "MCPTransport",
    # Datasource adapters + auto-profiling (Phase C)
    "DatasourceAdapter",
    "DatasourceItem",
    "DatasourceKind",
    "DatasourceStructure",
    "MCPDatasourceAdapter",
    "MCPEnumerator",
    "ResourceBindingAdapter",
    "ResourceBindingEnumerator",
    "DatasourceProfile",
    "NamingConvention",
    "profile_datasource",
    "DerivedToolSpec",
    "ToolInputSchema",
    "derive_datasource_tools",
    "apply_profile_to_datasource",
    # Per-client personalization (Phase D): chat -> spec -> seeded probes/judge
    "ClientSpec",
    "ExampleTask",
    "SpecElicitationError",
    "elicit_client_spec",
    "parse_client_spec",
    "example_task_probe_key",
    "spec_probe_keys",
    "make_spec_probe_synthesizer",
    "seed_probes_from_spec",
    "build_client_rubric",
    "build_client_criterion",
    "build_client_judge_test",
    # Per-client autoloop (Phase E): overlay compile + deep-tool-use run
    "ClientOverlay",
    "PersonalizedCompile",
    "build_client_prompt_block",
    "overlay_variant",
    "build_personalized_opencode_json",
    "write_personalized_opencode_json",
    "compile_personalized",
    "PersonalizationRun",
    "PersonalizationRunResult",
    "build_joint_mutators",
    "build_session_judge_evaluator",
    "contract_gate",
    "require_outcome",
    "require_tool_called",
    "require_any_tool_called",
    "require_artifact",
    "require_subagent_dispatched",
    "all_of",
    "RunOutcome",
    "ContractResult",
    "ContractPredicate",
    "ContextBlock",
    "PromptAssembler",
    "Volatility",
    "volatility_rank",
    "TaskHandle",
    "TaskKind",
    "TaskStatus",
    # Model presets
    "ModelLimits",
    "ModelPreset",
    "ReasoningField",
    "SamplingDefaults",
    # Mock surface
    "MockKind",
    "MockProfile",
    "MockResponse",
    "MockState",
    "Turn",
    # Testing primitives
    "AgentTest",
    "AnyEvaluator",
    "CapabilityTest",
    "EqualsEvaluator",
    "Evaluator",
    "EvaluatorKind",
    "JsonPathEvaluator",
    "LLMJudgeEvaluator",
    "PermissionAbsentEvaluator",
    "PermissionPresentEvaluator",
    "RegexEvaluator",
    "FactRecallEvaluator",
    "FactSpec",
    "PackProbe",
    "ProbePack",
    "load_pack",
    "pack_to_tests",
    "SubstringEvaluator",
    "ToolCalledEvaluator",
    "ToolNotCalledEvaluator",
    "PathOrderEvaluator",
    # branch (multi-agent path) tests
    "BranchTest",
    "StepContract",
    "BranchTrajectory",
    "BranchRunResult",
    "BranchInvoker",
    "run_branch_test",
    "evaluate_step_contracts",
    "scripted_invoker",
    "mock_chain_invoker",
    "assert_no_raw_provider_endpoints",
    "scan_repo_for_raw_provider_endpoints",
    "ToolTest",
    # Permissions
    "BashToolPermission",
    "DefaultTools",
    "JsonToolPermission",
    "Permission",
    "PermissionType",
    "ToolPermission",
    "ToolScope",
    # Skills
    "SkillDefinition",
    "SkillExample",
    "WorkflowStep",
    # Workflow steps
    "Criterion",
    "Gate",
    "GateCheck",
    "GateLogic",
    "Route",
    "ToolUse",
    "WorkflowStepDefinition",
    # Tools
    "ScriptDefinition",
    "SupportedScriptTypes",
    "ToolDefinition",
    "ToolDefinitionHeader",
    "ToolDefinitionLogicBash",
    "ToolDefinitionLogicJson",
    "ToolScriptDefinition",
    # Core tools
    "OpencodeManagerAction",
    "create_opencode_manager_tool",
    # Runtime
    "ScriptTool",
    "StreamFormat",
    "ResourceHandle",
    "SpawnAgentTool",
    "SpawnAgentInput",
    "SpawnAgentOutput",
]

__version__ = "1.4.0"
