"""Emitters: write SkillBundles to disk in dialect-specific layouts.

OpenCode:
  <target>/.opencode/skills/<bundle.name>/SKILL.md
  <target>/.opencode/skills/<bundle.name>/.skill_version  (sidecar)

Claude Code:
  <target>/.claude/skills/<bundle.name>/SKILL.md
  <target>/.claude/skills/<bundle.name>/.skill_version
  <target>/CLAUDE.md  (aggregated index pointing at every skill)

The .skill_version sidecar lets `oac sync-skills` detect when the
installed bundle is stale relative to the current package version.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from open_agent_compiler.skills.bundle import SkillBundle

DriftStatus = Literal["fresh", "stale", "missing"]


class EmissionResult(BaseModel):
    model_config = ConfigDict(frozen=False)

    target_dir: Path
    written: list[Path] = Field(default_factory=list)
    skipped_up_to_date: list[Path] = Field(default_factory=list)


def _frontmatter(bundle: SkillBundle) -> str:
    # Descriptions routinely contain colons — JSON-escape the values so
    # the frontmatter stays valid YAML for every consumer of the
    # cross-agent SKILL.md standard.
    import json

    lines = [
        "---",
        f"name: {bundle.name}",
        f"description: {json.dumps(bundle.description)}",
        f"version: {bundle.version}",
    ]
    if bundle.tools_hint:
        hint = ", ".join(bundle.tools_hint)
        lines.append(f"tools_hint: {json.dumps(hint)}")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def _skill_body(bundle: SkillBundle) -> str:
    return _frontmatter(bundle) + bundle.body_markdown.rstrip() + "\n"


def _read_version_sidecar(path: Path) -> str | None:
    if not path.exists():
        return None
    try:
        return path.read_text().strip()
    except OSError:
        return None


def _write_skill(
    bundle: SkillBundle, dir_path: Path, *, force: bool,
) -> tuple[list[Path], list[Path]]:
    """Common writer used by both opencode and claude targets.

    Skips when the sidecar already matches the bundle's content_hash
    (idempotent sync). force=True bypasses the check.
    """
    written: list[Path] = []
    skipped: list[Path] = []
    skill_md = dir_path / "SKILL.md"
    sidecar = dir_path / ".skill_version"
    current_hash = _read_version_sidecar(sidecar)
    if not force and current_hash == bundle.content_hash:
        skipped.extend([skill_md, sidecar])
        return written, skipped
    dir_path.mkdir(parents=True, exist_ok=True)
    skill_md.write_text(_skill_body(bundle))
    sidecar.write_text(bundle.content_hash)
    written.extend([skill_md, sidecar])
    return written, skipped


def emit_opencode(
    bundles: list[SkillBundle], target: Path, *, force: bool = False,
) -> EmissionResult:
    """Write bundles into <target>/.opencode/skills/."""
    out = EmissionResult(target_dir=target / ".opencode" / "skills")
    for b in bundles:
        if "opencode" not in b.targets:
            continue
        written, skipped = _write_skill(b, out.target_dir / b.name, force=force)
        out.written.extend(written)
        out.skipped_up_to_date.extend(skipped)
    return out


def _claude_md_index(bundles: list[SkillBundle]) -> str:
    """Aggregate index pointing at every emitted Claude skill."""
    lines = [
        "# Project skills",
        "",
        "This project uses skill bundles generated by `oac sync-skills`.",
        "Each skill below is a SKILL.md under `.claude/skills/<name>/`.",
        "",
    ]
    for b in sorted(bundles, key=lambda x: x.name):
        if "claude" not in b.targets:
            continue
        lines.append(f"- **{b.name}** (v{b.version}) — {b.description}")
        lines.append(f"  → `.claude/skills/{b.name}/SKILL.md`")
    lines.append("")
    return "\n".join(lines)


def emit_claude(
    bundles: list[SkillBundle], target: Path, *, force: bool = False,
) -> EmissionResult:
    """Write bundles into <target>/.claude/skills/ + a CLAUDE.md index."""
    out = EmissionResult(target_dir=target / ".claude" / "skills")
    for b in bundles:
        if "claude" not in b.targets:
            continue
        written, skipped = _write_skill(b, out.target_dir / b.name, force=force)
        out.written.extend(written)
        out.skipped_up_to_date.extend(skipped)
    # Aggregated index — always rewritten so it reflects the current set.
    claude_md = target / "CLAUDE.md"
    claude_md.write_text(_claude_md_index(bundles))
    out.written.append(claude_md)
    return out


def emit_pi(
    bundles: list[SkillBundle], target: Path, *, force: bool = False,
) -> EmissionResult:
    """Write bundles into <target>/.pi/skills/.

    pi discovers the cross-agent `<name>/SKILL.md` standard from
    `.pi/skills/` (pi-subagents "skill preloading"), so every bundle is
    emitted — the opencode/claude `targets` filter is a legacy of the
    two-dialect era, not a statement about pi.
    """
    out = EmissionResult(target_dir=target / ".pi" / "skills")
    for b in bundles:
        written, skipped = _write_skill(b, out.target_dir / b.name, force=force)
        out.written.extend(written)
        out.skipped_up_to_date.extend(skipped)
    return out


def emit_codex(
    bundles: list[SkillBundle], target: Path, *, force: bool = False,
) -> EmissionResult:
    """Write bundles into <target>/.codex/skills/.

    Codex scans `.codex/skills/<name>/SKILL.md` (one level deep, name +
    description frontmatter — the same cross-agent standard), loading
    full instructions on demand. Every bundle is emitted.
    """
    out = EmissionResult(target_dir=target / ".codex" / "skills")
    for b in bundles:
        written, skipped = _write_skill(b, out.target_dir / b.name, force=force)
        out.written.extend(written)
        out.skipped_up_to_date.extend(skipped)
    return out


class DriftReport(BaseModel):
    """Per-skill drift status for `oac sync-skills --check`."""

    model_config = ConfigDict(frozen=False)

    dialect: str
    skill_name: str
    status: DriftStatus
    installed_hash: str | None = None
    current_hash: str
    installed_version: str | None = None
    current_version: str


_SKILL_DIRS = {
    "opencode": ".opencode",
    "claude": ".claude",
    "pi": ".pi",
    "codex": ".codex",
}


def _dialect_dir(target: Path, dialect: str) -> Path:
    if dialect not in _SKILL_DIRS:
        raise ValueError(
            f"unknown skill dialect {dialect!r}; valid: {sorted(_SKILL_DIRS)}"
        )
    return target / _SKILL_DIRS[dialect] / "skills"


def check_drift(
    bundles: list[SkillBundle], target: Path, dialect: str,
) -> list[DriftReport]:
    """Inspect a target and report which skills are fresh / stale / missing.

    'fresh' — installed sidecar matches the current bundle's content_hash.
    'stale' — sidecar present but hash differs (re-sync recommended).
    'missing' — no sidecar / SKILL.md found for this skill.

    Works for all four dialects; pi/codex emit every bundle, so only
    opencode/claude apply the legacy `targets` filter (mirroring the
    emitters).
    """
    base = _dialect_dir(target, dialect)
    reports: list[DriftReport] = []
    for b in bundles:
        if dialect in ("opencode", "claude") and dialect not in b.targets:
            continue
        sidecar = base / b.name / ".skill_version"
        installed = _read_version_sidecar(sidecar)
        if installed is None:
            status: DriftStatus = "missing"
        elif installed == b.content_hash:
            status = "fresh"
        else:
            status = "stale"
        reports.append(DriftReport(
            dialect=dialect,
            skill_name=b.name,
            status=status,
            installed_hash=installed,
            current_hash=b.content_hash,
            installed_version=None,  # version is in the SKILL.md frontmatter; we don't parse for now
            current_version=b.version,
        ))
    return reports
