"""app/* + run.py generators — real FastAPI agent-invocation layer.

The scaffolded service does three things:
1. Exposes endpoints that spawn the compiled agent via `opencode run`.
2. Caches per-run state in memory (extendable to a DB).
3. Accepts the standardised cron event payload at /events/{id}/fire so
   the cron driver can stay dumb and just POST JSON.

Pattern mirrors mature production deployments of this framework: cron
and any other external trigger (webhook, scheduler, UI) hit FastAPI;
FastAPI is the single place that knows how to invoke agents.
"""

from __future__ import annotations

from open_agent_compiler.scaffold.config import ScaffoldConfig


def render_app_init(config: ScaffoldConfig) -> str:
    return f'"""FastAPI service for {config.project_name}."""\n'


def render_models(config: ScaffoldConfig) -> str:
    return (
        '"""Pydantic schemas shared by app routes + cron driver."""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "from typing import Any, Literal\n"
        "\n"
        "from pydantic import BaseModel, Field\n"
        "\n"
        "\n"
        "RunStatus = Literal[\n"
        "    'queued', 'running', 'completed', 'failed', 'unreachable'\n"
        "]\n"
        "\n"
        "\n"
        "RunMode = Literal[\n"
        "    # sync: block until the agent finishes; default for ≤30s work.\n"
        "    'sync',\n"
        "    # async: return run_id + poll_url immediately; caller polls\n"
        "    # /runs/{run_id}/await for the result.\n"
        "    'async',\n"
        "    # fire_and_forget: same as async but with no expectation the\n"
        "    # caller will check back; an optional callback_url is POSTed\n"
        "    # the final AgentRunResult when the run terminates.\n"
        "    'fire_and_forget',\n"
        "]\n"
        "\n"
        "\n"
        "RetryTrigger = Literal[\n"
        "    'always',     # try this step unconditionally\n"
        "    'on_failure', # try only when the previous attempt failed\n"
        "    'on_timeout', # try only when the previous attempt timed out\n"
        "]\n"
        "\n"
        "\n"
        "class RetryStep(BaseModel):\n"
        '    """One step in a retry chain — pick a variant + when to use it."""\n'
        "    variant: str | None = Field(\n"
        "        default=None,\n"
        "        description=\"Compiled variant for this attempt; None = default.\",\n"
        "    )\n"
        "    timeout_s: float = 60.0\n"
        "    when: RetryTrigger = 'on_failure'\n"
        "    note: str | None = Field(\n"
        "        default=None,\n"
        "        description=\"Free-form label surfaced in the run's fallback_chain.\",\n"
        "    )\n"
        "\n"
        "\n"
        "class RetryPolicy(BaseModel):\n"
        '    """Ordered, composable chain of RetrySteps.\n'
        "\n"
        "    The dispatcher tries steps in order, skipping any whose\n"
        "    `when` condition doesn't match the previous outcome. A\n"
        "    successful attempt short-circuits the chain.\n"
        '    """\n'
        "    steps: list[RetryStep] = Field(default_factory=list)\n"
        "\n"
        "    @classmethod\n"
        "    def linear(\n"
        "        cls, variants: list[str | None],\n"
        "        *, timeout_s: float = 60.0,\n"
        "    ) -> 'RetryPolicy':\n"
        '        """Shorthand: try each variant in order, each on previous failure."""\n'
        "        return cls(steps=[\n"
        "            RetryStep(\n"
        "                variant=v, timeout_s=timeout_s,\n"
        "                when='always' if i == 0 else 'on_failure',\n"
        "            )\n"
        "            for i, v in enumerate(variants)\n"
        "        ])\n"
        "\n"
        "\n"
        "class AgentRunRequest(BaseModel):\n"
        '    """POST /agents/{name}/run body."""\n'
        "    prompt: str\n"
        "    context: dict[str, Any] | None = None\n"
        "    run_id: str | None = Field(\n"
        "        default=None,\n"
        '        description=\"Caller-supplied id; auto-generated when omitted.\",\n'
        "    )\n"
        "    timeout_s: float = 300.0\n"
        "    mode: RunMode = Field(\n"
        "        default='sync',\n"
        "        description=(\n"
        "            \"sync (default) blocks until done; async returns the run_id\"\n"
        "            \" + poll_url immediately; fire_and_forget runs detached and\"\n"
        "            \" optionally POSTs the result to callback_url.\"\n"
        "        ),\n"
        "    )\n"
        "    callback_url: str | None = Field(\n"
        "        default=None,\n"
        "        description=(\n"
        "            \"Honoured when mode='fire_and_forget'. When the run\"\n"
        "            \" terminates the server POSTs the AgentRunResult here.\"\n"
        "        ),\n"
        "    )\n"
        "    variant: str | None = Field(\n"
        "        default=None,\n"
        "        description=(\n"
        "            \"Pick a specific compiled variant of this agent\"\n"
        "            \" (e.g. 'fast' / 'smart' / 'permodel-analytical').\"\n"
        "            \" The runner first looks for <name>-<variant>.md\"\n"
        "            \" under build/.opencode/agents/, then falls back to\"\n"
        "            \" <name>.md. Use to route a single logical agent\"\n"
        "            \" name to different compiled trees per call —\"\n"
        "            \" the FastAPI is the abstraction layer over the\"\n"
        "            \" multiple physical compiles sitting in build/.\"\n"
        "        ),\n"
        "    )\n"
        "    retry: RetryPolicy | None = Field(\n"
        "        default=None,\n"
        "        description=(\n"
        "            \"Composable retry chain. When set, supersedes the\"\n"
        "            \" simple `variant` field. The dispatcher walks each\"\n"
        "            \" RetryStep in order, picking the variant + timeout,\"\n"
        "            \" skipping steps whose `when` doesn't match the\"\n"
        "            \" previous outcome. Use RetryPolicy.linear([...])\"\n"
        "            \" for the common fast→smart→external pattern.\"\n"
        "        ),\n"
        "    )\n"
        "\n"
        "\n"
        "class AgentRunResult(BaseModel):\n"
        '    """Returned by POST /agents/{name}/run + GET /runs/{run_id}."""\n'
        "    run_id: str\n"
        "    agent: str\n"
        "    status: RunStatus\n"
        "    return_code: int | None = None\n"
        "    stdout: str = ''\n"
        "    stderr: str = ''\n"
        "    duration_s: float = 0.0\n"
        "    log_path: str | None = None\n"
        "    started_at: str | None = None\n"
        "    finished_at: str | None = None\n"
        "    error: str | None = None\n"
        "    resolved_variant: str | None = Field(\n"
        "        default=None,\n"
        "        description=(\n"
        "            \"Which physical variant ran (e.g. 'fast'). None means\"\n"
        "            \" the default <name>.md was used.\"\n"
        "        ),\n"
        "    )\n"
        "    fallback_chain: list[dict[str, Any]] = Field(\n"
        "        default_factory=list,\n"
        "        description=(\n"
        "            \"Per-attempt records when the dispatcher escalated\"\n"
        "            \" through fallback_variants. Each entry:\"\n"
        "            \" {variant, status, return_code, error}.\"\n"
        "        ),\n"
        "    )\n"
        "\n"
        "\n"
        "class CronEvent(BaseModel):\n"
        '    """Standardised JSON event shape.\n'
        "\n"
        "    Lives in <project>/cron/events.json (or wherever\n"
        "    --cron-events points). The cron driver matches `schedule`\n"
        "    against the current minute and POSTs the event to\n"
        "    /events/{id}/fire; this route dispatches `agent` with\n"
        '    `prompt` and any extra `context`.\n'
        '    """\n'
        "    id: str\n"
        "    schedule: str\n"
        "    agent: str\n"
        "    prompt: str\n"
        "    context: dict[str, Any] | None = None\n"
        "    enabled: bool = True\n"
        "\n"
        "\n"
        "class HealthResponse(BaseModel):\n"
        "    status: Literal['ok'] = 'ok'\n"
        "    project: str\n"
        "    agents_available: int\n"
    )


def render_agent_runner(config: ScaffoldConfig) -> str:
    return (
        '"""Spawn `opencode run` (or a fallback) and capture results.\n'
        "\n"
        "Conventions:\n"
        "- Per-run state is held in-memory (RUNS dict). Replace with\n"
        "  the bundled subagent_todo + a DB when you need persistence.\n"
        "- Logs land under run_logs/<run_id>.log so the operator can\n"
        "  tail them while the agent is running.\n"
        "- XDG_DATA_HOME is forced to ./.opencode/data so the agent's\n"
        "  sessions show up in the opencode-web UI on the same project.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "import asyncio\n"
        "import os\n"
        "import uuid\n"
        "from datetime import datetime\n"
        "from pathlib import Path\n"
        "\n"
        "from app.models import AgentRunRequest, AgentRunResult\n"
        "\n"
        "PROJECT_ROOT = Path(__file__).resolve().parent.parent\n"
        "BUILD_DIR = PROJECT_ROOT / 'build'\n"
        "LOGS_DIR = PROJECT_ROOT / 'run_logs'\n"
        "\n"
        "# Tracks the most recent state of every run keyed by run_id.\n"
        "# In production swap for a DB-backed store.\n"
        "RUNS: dict[str, AgentRunResult] = {}\n"
        "\n"
        "\n"
        "def _resolve_agent_md(\n"
        "    name: str, variant: str | None = None,\n"
        ") -> tuple[Path | None, str | None]:\n"
        '    """Find build/.opencode/agents/<name>[-<variant>].md.\n'
        "\n"
        "    Returns (path, resolved_variant). resolved_variant is the\n"
        "    requested variant when the variant-specific file was found,\n"
        '    otherwise None (the default <name>.md was used).\n'
        '    """\n'
        "    agents_dir = BUILD_DIR / '.opencode' / 'agents'\n"
        "    if variant:\n"
        "        variant_path = agents_dir / f'{name}-{variant}.md'\n"
        "        if variant_path.exists():\n"
        "            return variant_path, variant\n"
        "    direct = agents_dir / f'{name}.md'\n"
        "    if direct.exists():\n"
        "        return direct, None\n"
        "    for path in agents_dir.rglob('*.md'):\n"
        "        if path.stem == name or path.relative_to(\n"
        "            agents_dir\n"
        "        ).as_posix() == f'{name}.md':\n"
        "            return path, None\n"
        "    return None, None\n"
        "\n"
        "\n"
        "def list_compiled_agents() -> list[str]:\n"
        "    agents_dir = BUILD_DIR / '.opencode' / 'agents'\n"
        "    if not agents_dir.exists():\n"
        "        return []\n"
        "    rels = []\n"
        "    for p in agents_dir.rglob('*.md'):\n"
        "        rel = p.relative_to(agents_dir).as_posix()\n"
        "        rels.append(rel.removesuffix('.md'))\n"
        "    return sorted(rels)\n"
        "\n"
        "\n"
        "def _opencode_data_home() -> str:\n"
        '    """opencode reads + writes session state under'
        " XDG_DATA_HOME/opencode/.\n"
        "\n"
        "    Default points at BUILD_DIR (not PROJECT_ROOT) — opencode\n"
        "    also looks for .opencode/agents/ relative to the data home\n"
        "    so the compiled agents are discoverable. Pointing this at\n"
        "    PROJECT_ROOT causes 'Agent not found' errors that fall back\n"
        '    to opencode\'s built-in agents.\n'
        '    """\n'
        "    xdg = os.environ.get('XDG_DATA_HOME')\n"
        "    return xdg if xdg else str(BUILD_DIR / '.opencode' / 'data')\n"
        "\n"
        "\n"
        "async def run_agent(agent: str, req: AgentRunRequest) -> AgentRunResult:\n"
        '    """Spawn the agent as an opencode subprocess and capture stdout/stderr."""\n'
        "    run_id = req.run_id or uuid.uuid4().hex[:12]\n"
        "    start = datetime.now()\n"
        "    state = AgentRunResult(\n"
        "        run_id=run_id, agent=agent, status='running',\n"
        "        started_at=start.isoformat(timespec='seconds'),\n"
        "    )\n"
        "    RUNS[run_id] = state\n"
        "\n"
        "    md, resolved_variant = _resolve_agent_md(agent, req.variant)\n"
        "    state.resolved_variant = resolved_variant\n"
        "    if md is None:\n"
        "        state.status = 'failed'\n"
        "        state.error = (\n"
        "            f'agent {agent!r} (variant={req.variant!r}) not found'\n"
        "            f' in build/.opencode/agents/'\n"
        "        )\n"
        "        state.finished_at = datetime.now().isoformat(timespec='seconds')\n"
        "        return state\n"
        "\n"
        "    LOGS_DIR.mkdir(parents=True, exist_ok=True)\n"
        "    log_path = LOGS_DIR / f'{agent.replace(\"/\", \"_\")}_{run_id}.log'\n"
        "    state.log_path = str(log_path)\n"
        "\n"
        "    env = os.environ.copy()\n"
        "    env['XDG_DATA_HOME'] = _opencode_data_home()\n"
        "    # opencode discovers .opencode/agents/<name>.md relative\n"
        "    # to PWD. Without this, opencode falls back to its built-in\n"
        "    # agents (build / explore / general / plan) and reports our\n"
        '    # compiled agents as "Agent not found".\n'
        "    env['PWD'] = str(BUILD_DIR)\n"
        "    # Surface event context to ScriptTools via env (e.g. an\n"
        "    # e-commerce app's ECOM_* vars — namespace per project as needed).\n"
        "    if req.context:\n"
        "        for k, v in req.context.items():\n"
        "            env[f'OAC_CTX_{k.upper()}'] = str(v)\n"
        "\n"
        "    # Use the resolved file's stem so a variant-suffixed file\n"
        "    # actually drives opencode (--agent foo-fast → foo-fast.md).\n"
        "    rel = md.relative_to(BUILD_DIR / '.opencode' / 'agents')\n"
        "    effective_agent = rel.as_posix().removesuffix('.md')\n"
        "    cmd = [\n"
        "        'opencode', 'run',\n"
        "        '--agent', effective_agent,\n"
        "        req.prompt,\n"
        "    ]\n"
        "    try:\n"
        "        proc = await asyncio.create_subprocess_exec(\n"
        "            # cwd MUST be BUILD_DIR so opencode finds\n"
        "            # .opencode/agents/<name>.md (including the\n"
        "            # -primary variants from also_compile_as_primary).\n"
        "            *cmd, cwd=str(BUILD_DIR), env=env,\n"
        "            # stdin MUST be DEVNULL — opencode blocks waiting\n"
        "            # for input when launched with a PIPE-connected\n"
        "            # stdin even though it never reads from it.\n"
        "            stdin=asyncio.subprocess.DEVNULL,\n"
        "            stdout=asyncio.subprocess.PIPE,\n"
        "            stderr=asyncio.subprocess.PIPE,\n"
        "        )\n"
        "        try:\n"
        "            stdout, stderr = await asyncio.wait_for(\n"
        "                proc.communicate(), timeout=req.timeout_s,\n"
        "            )\n"
        "        except asyncio.TimeoutError:\n"
        "            proc.kill()\n"
        "            await proc.communicate()\n"
        "            state.status = 'failed'\n"
        "            state.error = f'timed out after {req.timeout_s}s'\n"
        "            state.finished_at = datetime.now().isoformat(timespec='seconds')\n"
        "            state.duration_s = (datetime.now() - start).total_seconds()\n"
        "            log_path.write_text(\n"
        "                f'[TIMEOUT] {state.error}\\n'\n"
        "            )\n"
        "            return state\n"
        "        rc = proc.returncode or 0\n"
        "    except FileNotFoundError:\n"
        "        state.status = 'failed'\n"
        "        state.error = (\n"
        "            \"'opencode' binary not found in PATH; install it or wire \"\n"
        "            'a different runtime in app/agent_runner.py'\n"
        "        )\n"
        "        state.finished_at = datetime.now().isoformat(timespec='seconds')\n"
        "        log_path.write_text(f'[ERROR] {state.error}\\n')\n"
        "        return state\n"
        "    except Exception as exc:  # noqa: BLE001\n"
        "        state.status = 'failed'\n"
        "        state.error = f'subprocess raised: {exc}'\n"
        "        state.finished_at = datetime.now().isoformat(timespec='seconds')\n"
        "        log_path.write_text(f'[ERROR] {state.error}\\n')\n"
        "        return state\n"
        "\n"
        "    finished = datetime.now()\n"
        "    state.stdout = stdout.decode('utf-8', errors='replace')\n"
        "    state.stderr = stderr.decode('utf-8', errors='replace')\n"
        "    state.return_code = rc\n"
        "    state.status = 'completed' if rc == 0 else 'failed'\n"
        "    state.duration_s = (finished - start).total_seconds()\n"
        "    state.finished_at = finished.isoformat(timespec='seconds')\n"
        "    log_path.write_text(\n"
        "        f'AGENT={agent}\\nRUN_ID={run_id}\\nRC={rc}\\n'\n"
        "        f'DURATION={state.duration_s:.2f}s\\n'\n"
        "        f'--- PROMPT ---\\n{req.prompt}\\n'\n"
        "        f'--- STDOUT ---\\n{state.stdout}\\n'\n"
        "        f'--- STDERR ---\\n{state.stderr}\\n'\n"
        "    )\n"
        "    return state\n"
    )


def render_app_main(config: ScaffoldConfig) -> str:
    # Conditional persistence wiring. When postgres is on, the
    # runs router + persistence wrapper are emitted (Phase 18); the
    # run_one route then calls record_run(...) so every invocation
    # lands in the `runs` table.
    persistence_imports = (
        "from app.persistence import record_run\n"
        "from app.runs import router as runs_router\n"
    ) if config.with_postgres else ""
    # Phase 23: the route calls the dispatcher (mode-aware wrapper)
    # rather than run_agent / record_run directly. The dispatcher
    # branches sync vs async vs fire_and_forget.
    persistence_run_call = (
        "    return await dispatch_run(name, req, run_agent, with_persistence=True)"
    ) if config.with_postgres else (
        "    return await dispatch_run(name, req, run_agent, with_persistence=False)"
    )
    persistence_include = (
        "app.include_router(runs_router)\n\n\n"
    ) if config.with_postgres else ""
    persistence_event_call = (
        "    return await dispatch_run(event.agent, req, run_agent, with_persistence=True)"
    ) if config.with_postgres else (
        "    return await dispatch_run(event.agent, req, run_agent, with_persistence=False)"
    )
    # Phase F: the saas-personalized template exposes the per-client
    # intake / personalize / serve surface on a dedicated router.
    personalize_import = (
        "from app.personalize import router as personalize_router\n"
    ) if config.is_personalized else ""
    personalize_include = (
        "app.include_router(personalize_router)\n\n\n"
    ) if config.is_personalized else ""
    return (
        '"""FastAPI entrypoint with real agent-invocation routes.\n'
        "\n"
        "Every external trigger (cron, webhook, UI, another service)\n"
        "POSTs here. The runner spawns `opencode run` and captures\n"
        "stdout/stderr/log_path.\n"
        '"""\n'
        "\n"
        "from contextlib import asynccontextmanager\n"
        "\n"
        "from fastapi import FastAPI, HTTPException\n"
        "\n"
        "from app.agent_runner import (\n"
        "    BUILD_DIR,\n"
        "    RUNS,\n"
        "    list_compiled_agents,\n"
        "    run_agent,\n"
        ")\n"
        "from app.models import (\n"
        "    AgentRunRequest,\n"
        "    AgentRunResult,\n"
        "    CronEvent,\n"
        "    HealthResponse,\n"
        ")\n"
        "from app.dispatch import dispatch_run\n"
        f"{persistence_imports}"
        f"{personalize_import}"
        "\n"
        "\n"
        "@asynccontextmanager\n"
        "async def lifespan(app: FastAPI):\n"
        "    if not (BUILD_DIR / '.opencode' / 'agents').exists():\n"
        "        raise RuntimeError(\n"
        "            'build/.opencode/agents missing — run `uv run python build_agents.py` first'\n"
        "        )\n"
        "    yield\n"
        "\n"
        "\n"
        f"app = FastAPI(title='{config.project_name}', lifespan=lifespan)\n"
        f"{persistence_include if persistence_include else chr(10)}"
        f"{personalize_include}"
        "\n"
        "@app.get('/health', response_model=HealthResponse)\n"
        "async def health() -> HealthResponse:\n"
        "    return HealthResponse(\n"
        f"        project='{config.project_name}',\n"
        "        agents_available=len(list_compiled_agents()),\n"
        "    )\n"
        "\n"
        "\n"
        "@app.get('/agents', response_model=list[str])\n"
        "async def agents() -> list[str]:\n"
        "    return list_compiled_agents()\n"
        "\n"
        "\n"
        "@app.post('/agents/{name:path}/run', response_model=AgentRunResult)\n"
        "async def run_one(name: str, req: AgentRunRequest) -> AgentRunResult:\n"
        "    if name not in list_compiled_agents():\n"
        "        raise HTTPException(status_code=404, detail=f'agent {name!r} not compiled')\n"
        f"{persistence_run_call}\n"
        "\n"
        "\n"
        "@app.get('/runs/{run_id}', response_model=AgentRunResult)\n"
        "async def get_run(run_id: str) -> AgentRunResult:\n"
        "    result = RUNS.get(run_id)\n"
        "    if result is None:\n"
        "        raise HTTPException(status_code=404, detail=f'run {run_id!r} not found')\n"
        "    return result\n"
        "\n"
        "\n"
        "@app.post('/events/{event_id}/fire', response_model=AgentRunResult)\n"
        "async def fire_event(event_id: str, event: CronEvent) -> AgentRunResult:\n"
        '    """Cron driver target. Treats the event payload as authoritative.\n'
        "\n"
        "    The cron service POSTs this with the event JSON it matched.\n"
        "    Disabled events still 200; the runner is a no-op when\n"
        "    event.enabled is False so cron logs stay clean.\n"
        '    """\n'
        "    if not event.enabled:\n"
        "        return AgentRunResult(\n"
        "            run_id=f'noop-{event_id}', agent=event.agent,\n"
        "            status='completed', stdout='event disabled',\n"
        "        )\n"
        "    req = AgentRunRequest(\n"
        "        prompt=event.prompt,\n"
        "        context={**(event.context or {}), 'event_id': event_id},\n"
        "    )\n"
        f"{persistence_event_call}\n"
    )


def render_run_py(config: ScaffoldConfig) -> str:
    return (
        '"""Uvicorn launcher reading HOST/PORT from env."""\n'
        "\n"
        "import os\n"
        "\n"
        "import uvicorn\n"
        "\n"
        "if __name__ == '__main__':\n"
        "    uvicorn.run(\n"
        "        'app.main:app',\n"
        "        host=os.environ.get('HOST', '0.0.0.0'),\n"
        "        port=int(os.environ.get('PORT', '8002')),\n"
        "        reload=os.environ.get('UVICORN_RELOAD', '0') == '1',\n"
        "    )\n"
    )
