"""Generator for improve/ — the autoloop starter (goals + runner).

The optimization flow needs to know WHAT the agent should do and HOW to
measure it. `improve/goals.yaml` is the collected answer — the
autoloop-interview developer skill walks the user through filling it —
and `improve/run_improve.py` turns it into a per-target loop run with
the SQLite store recording history and winners promoted per target.
"""

from __future__ import annotations

from open_agent_compiler.scaffold.config import ScaffoldConfig


def render_goals(config: ScaffoldConfig) -> str:
    return (
        "# Optimization goals for this project's agents.\n"
        "# Fill this in (or let the autoloop-interview skill fill it with you:\n"
        "# ask your coding agent to 'interview me for the autoloop goals').\n"
        "# improve/run_improve.py reads it.\n"
        "\n"
        "component: primary          # which agent/tool to optimize\n"
        "\n"
        "# What should the agent accomplish? One sentence, outcome-focused.\n"
        "goal: >-\n"
        "  TODO: e.g. \"Answer support questions concisely with a concrete\n"
        "  next step for the user.\"\n"
        "\n"
        "# Where must it perform? Each entry is harness[+model_class].\n"
        "targets:\n"
        f"  - {config.dialect}\n"
        "  - interactive\n"
        "\n"
        "# Probes: realistic inputs + how to judge the output.\n"
        "# kinds: substring (needle), llm_judge (criteria in plain language).\n"
        "probes:\n"
        "  - id: greets\n"
        "    prompt: \"TODO: a realistic user input\"\n"
        "    judge:\n"
        "      kind: llm_judge\n"
        "      criteria: \"TODO: what a GOOD answer looks like, in plain language\"\n"
        "  - id: stays-on-topic\n"
        "    prompt: \"TODO: a tricky/adversarial input\"\n"
        "    judge:\n"
        "      kind: substring\n"
        "      needle: \"TODO: a string a correct answer must contain\"\n"
        "\n"
        "# Hard floor: candidates below this pass-rate never promote.\n"
        "pass_rate_floor: 0.8\n"
        "rounds: 2\n"
    )


def render_run_improve(config: ScaffoldConfig) -> str:
    return (
        '"""Run per-target autoloops from improve/goals.yaml.\n'
        "\n"
        "    uv run python improve/run_improve.py            # all targets\n"
        "    uv run python improve/run_improve.py --dry-run   # show the plan\n"
        "\n"
        "Reads goals.yaml (component, targets, probes, floor), runs one loop\n"
        "per target — compiled targets via build_compiled_evaluator (real\n"
        "harness runs), the interactive target via build_interactive_evaluator\n"
        "— records every candidate in .oac/improvement.db, and promotes each\n"
        "target's winner into its slot. Browse afterwards:\n"
        "\n"
        "    uv run oac versions list <component>\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "import sys\n"
        "from pathlib import Path\n"
        "\n"
        "import yaml\n"
        "\n"
        "PROJECT_ROOT = Path(__file__).resolve().parent.parent\n"
        "sys.path.insert(0, str(PROJECT_ROOT))\n"
        "\n"
        "from agents.registry import registry  # noqa: E402\n"
        "from open_agent_compiler import build_interactive_spec  # noqa: E402\n"
        "from open_agent_compiler.improvement import (  # noqa: E402\n"
        "    Criterion,\n"
        "    IdentityMutator,\n"
        "    OptimisationCriterion,\n"
        "    OptimizationTarget,\n"
        "    Probe,\n"
        "    PromptPrefixMutator,\n"
        "    Snapshot,\n"
        "    build_compiled_evaluator,\n"
        "    build_interactive_evaluator,\n"
        "    open_store,\n"
        "    promote,\n"
        "    run_per_target_loops,\n"
        ")\n"
        "from open_agent_compiler.improvement.version import ComponentVersion  # noqa: E402\n"
        "from open_agent_compiler.model.core.test_model import (  # noqa: E402\n"
        "    LLMJudgeEvaluator,\n"
        "    SubstringEvaluator,\n"
        ")\n"
        "\n"
        "GOALS = yaml.safe_load((PROJECT_ROOT / \"improve\" / \"goals.yaml\").read_text())\n"
        "\n"
        "\n"
        "def _probe(entry: dict) -> Probe:\n"
        "    judge = entry.get(\"judge\", {})\n"
        "    if judge.get(\"kind\") == \"substring\":\n"
        "        evaluators = (SubstringEvaluator(needle=judge[\"needle\"]),)\n"
        "    else:\n"
        "        evaluators = (LLMJudgeEvaluator(criteria=judge.get(\"criteria\", \"\")),)\n"
        "    return Probe(probe_id=entry[\"id\"], payload=entry[\"prompt\"],\n"
        "                 evaluators=evaluators)\n"
        "\n"
        "\n"
        "def _target(spec: str) -> OptimizationTarget:\n"
        "    harness, _, model_class = spec.partition(\"+\")\n"
        "    return OptimizationTarget(harness=harness,\n"
        "                              model_class=model_class or None)\n"
        "\n"
        "\n"
        "def _registry_factory(defn: dict):\n"
        "    # Rebuild the registry with the candidate's mutated prompt via the\n"
        "    # generated registry()'s override hook. Extend the override as your\n"
        "    # registry grows (see docs: guides/optimization-targets.md).\n"
        "    return registry(system_prompt=str(defn.get(\"system_prompt\", \"\")) or None)\n"
        "\n"
        "\n"
        "def _live_profile():\n"
        "    from open_agent_compiler.model.core.model_preset import (\n"
        "        ModelPreset, SamplingDefaults,\n"
        "    )\n"
        "    from open_agent_compiler.model.core.split_profile import SplitProfile\n"
        "    import os\n"
        "    preset = ModelPreset(\n"
        "        name=\"live\", provider=\"live\",\n"
        "        model_id=os.environ.get(\"LIVE_MODEL_ID\", \"gpt-4o-mini\"),\n"
        "        sampling=SamplingDefaults(temperature=0.4),\n"
        "        provider_options={\n"
        "            \"base_url\": os.environ.get(\"LIVE_BASE_URL\", \"\"),\n"
        "            \"api_key_env\": \"LIVE_API_KEY\",\n"
        "        },\n"
        "    )\n"
        "    return SplitProfile(name=\"live\", preset=preset,\n"
        "                        class_map={\"default\": preset})\n"
        "\n"
        "\n"
        "def main() -> None:\n"
        "    dry = \"--dry-run\" in sys.argv\n"
        "    component = GOALS.get(\"component\", \"primary\")\n"
        "    probes = [_probe(p) for p in GOALS.get(\"probes\", [])]\n"
        "    targets = [_target(t) for t in GOALS.get(\"targets\", [])]\n"
        "    if dry:\n"
        "        print(f\"component: {component}\")\n"
        "        print(f\"targets:   {[t.key for t in targets]}\")\n"
        "        print(f\"probes:    {[p.probe_id for p in probes]}\")\n"
        "        return\n"
        "\n"
        "    reg = registry()\n"
        "    resolved = reg.resolve_config(\"prod\")\n"
        "    variant = resolved.get(component) or next(iter(resolved.values()))\n"
        "    baseline = ComponentVersion.of(\n"
        "        component_id=component, kind=\"agent\",\n"
        "        definition={\"system_prompt\": variant.agent_definition.system_prompt},\n"
        "    )\n"
        "\n"
        "    def evaluator_factory(target: OptimizationTarget):\n"
        "        if target.harness == \"interactive\":\n"
        "            # TODO: pass judge=YourJudge() and a live profile; see\n"
        "            # docs guides/optimization-targets.md for the wiring.\n"
        "            def spec_factory(defn: dict):\n"
        "                agent = variant.agent_definition.model_copy(\n"
        "                    update={\"system_prompt\": str(defn.get(\"system_prompt\", \"\"))})\n"
        "                return build_interactive_spec(\n"
        "                    agent=agent, live_profile=_live_profile())\n"
        "            return build_interactive_evaluator(probes, spec_factory)\n"
        "        return build_compiled_evaluator(\n"
        "            probes,\n"
        "            registry_factory=_registry_factory,\n"
        "            target=target,\n"
        "            build_dir=PROJECT_ROOT / \"eval_build\" / target.key,\n"
        "            config=\"prod\",\n"
        "            agent_name=component,\n"
        "        )\n"
        "\n"
        "    store = open_store(project_root=PROJECT_ROOT)\n"
        "    results = run_per_target_loops(\n"
        "        baseline=baseline,\n"
        "        mutators=[IdentityMutator(),\n"
        "                  PromptPrefixMutator(\"Be concise and concrete. \")],\n"
        "        criterion=OptimisationCriterion(\n"
        "            name=\"goals\",\n"
        "            criteria=(Criterion(kind=\"pass_rate\",\n"
        "                                target=float(GOALS.get(\"pass_rate_floor\", 0.8)),\n"
        "                                hard=True),),\n"
        "        ),\n"
        "        targets=targets,\n"
        "        evaluator_factory=evaluator_factory,\n"
        "        max_rounds=int(GOALS.get(\"rounds\", 2)),\n"
        "        output=PROJECT_ROOT / \"improved\",\n"
        "        store=store,\n"
        "    )\n"
        "    for key in results:\n"
        "        latest = PROJECT_ROOT / \"improved\" / component / key / \"LATEST.json\"\n"
        "        if not latest.exists():\n"
        "            print(f\"{key}: no winner cleared the floor\")\n"
        "            continue\n"
        "        snap = Snapshot.model_validate_json(latest.read_text())\n"
        "        promote(latest, PROJECT_ROOT, target=key, force=True, store=store)\n"
        "        print(f\"{key}: promoted {snap.version.content_hash[:12]}\")\n"
        "\n"
        "\n"
        'if __name__ == "__main__":\n'
        "    main()\n"
    )
