"""Generator for telegram_bot/ — the realtime chat service.

The compose file has always declared a `telegram-bot` service running
`python -m telegram_bot.bot`; this module generates that package. The
bot is the REALTIME tier: an in-process interactive agent
(`run_interactive`) answering each Telegram message, with per-chat
history persisted in SQLite and a `spawn_worker` tool that dispatches
long jobs to the compiled workers through the dialect-agnostic harness
adapter (app/harness.py).
"""

from __future__ import annotations

from open_agent_compiler.scaffold.config import ScaffoldConfig


def render_package_init(config: ScaffoldConfig) -> str:
    return '"""Telegram realtime-chat service (generated by oac init)."""\n'


def render_bot(config: ScaffoldConfig) -> str:
    return (
        '"""Realtime Telegram chat over the project\'s agents.\n'
        "\n"
        "Architecture (the two-tier pattern):\n"
        "- THIS process is the interactive tier: run_interactive answers each\n"
        "  message in-process against the LIVE provider (env: LIVE_MODEL_ID,\n"
        "  LIVE_BASE_URL, LIVE_API_KEY), threading per-chat history from the\n"
        "  chat_history SQLite table (.oac/telegram.db).\n"
        "- Long, side-effecting jobs go to the compiled WORKERS: the agent\n"
        "  holds one `spawn_worker` tool routed through app.harness, so any\n"
        "  compiled agent in build/ is one tool call away, on whatever\n"
        "  harness this project compiles for.\n"
        "\n"
        "Env: TELEGRAM_BOT_TOKEN (from @BotFather) — see .env.example.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "import asyncio\n"
        "import json\n"
        "import os\n"
        "import sqlite3\n"
        "from pathlib import Path\n"
        "\n"
        "from telegram import Update\n"
        "from telegram.ext import (\n"
        "    Application, ContextTypes, MessageHandler, filters,\n"
        ")\n"
        "\n"
        "from agents.registry import registry\n"
        "from app.harness import run_compiled_agent\n"
        "from open_agent_compiler import build_interactive_spec\n"
        "from open_agent_compiler.interactive.runner import run_interactive\n"
        "from open_agent_compiler.interactive.spec import ToolSpec\n"
        "from open_agent_compiler.model.core.model_preset import (\n"
        "    ModelPreset, SamplingDefaults,\n"
        ")\n"
        "from open_agent_compiler.model.core.split_profile import SplitProfile\n"
        "\n"
        "PROJECT_ROOT = Path(__file__).resolve().parent.parent\n"
        'DB_PATH = PROJECT_ROOT / ".oac" / "telegram.db"\n'
        "HISTORY_TURNS = 20  # messages of context per chat\n"
        "\n"
        "\n"
        "def _live_profile() -> SplitProfile:\n"
        '    """The interactive tier\'s provider, from env (OpenAI-compatible)."""\n'
        "    preset = ModelPreset(\n"
        '        name="live",\n'
        '        provider="live",\n'
        '        model_id=os.environ.get("LIVE_MODEL_ID", "gpt-4o-mini"),\n'
        "        sampling=SamplingDefaults(temperature=0.4),\n"
        "        provider_options={\n"
        '            "base_url": os.environ.get("LIVE_BASE_URL", ""),\n'
        '            "api_key_env": "LIVE_API_KEY",\n'
        "        },\n"
        "    )\n"
        '    return SplitProfile(name="live", preset=preset,\n'
        '                        class_map={"default": preset})\n'
        "\n"
        "\n"
        "def _build_spec():\n"
        '    """Interactive spec for the primary agent + the spawn_worker tool."""\n'
        "    reg = registry()\n"
        '    resolved = reg.resolve_config("prod")\n'
        '    variant = resolved.get("primary") or next(iter(resolved.values()))\n'
        "    agent = variant.agent_definition\n"
        "    spec = build_interactive_spec(agent=agent, live_profile=_live_profile())\n"
        "    spawn = ToolSpec(\n"
        '        name="spawn_worker",\n'
        "        description=(\n"
        '            "Run a compiled worker agent for long tasks. Args: agent\\n'
        '(compiled agent name, e.g. primary), prompt (the task)."\n'
        "        ),\n"
        "        input_schema={\n"
        '            "type": "object",\n'
        '            "properties": {\n'
        '                "agent": {"type": "string"},\n'
        '                "prompt": {"type": "string"},\n'
        "            },\n"
        '            "required": ["agent", "prompt"],\n'
        "        },\n"
        "    )\n"
        "    return spec.model_copy(update={\"tools\": (*spec.tools, spawn)})\n"
        "\n"
        "\n"
        "def _tool_runner(name: str, args: dict) -> str:\n"
        '    if name == "spawn_worker":\n'
        '        return run_compiled_agent(\n'
        '            str(args.get("agent", "primary")), str(args.get("prompt", "")),\n'
        "        )\n"
        '    raise RuntimeError(f"unknown tool {name!r}")\n'
        "\n"
        "\n"
        "# --- per-chat history (SQLite) -----------------------------------\n"
        "\n"
        "def _connect() -> sqlite3.Connection:\n"
        "    DB_PATH.parent.mkdir(parents=True, exist_ok=True)\n"
        "    conn = sqlite3.connect(DB_PATH)\n"
        "    conn.execute(\n"
        '        "CREATE TABLE IF NOT EXISTS chat_history ("\n'
        '        " chat_id TEXT, role TEXT, content TEXT,"\n'
        '        " ts REAL DEFAULT (unixepoch()))"\n'
        "    )\n"
        "    return conn\n"
        "\n"
        "\n"
        "def _history(chat_id: str) -> list[dict]:\n"
        "    with _connect() as conn:\n"
        "        rows = conn.execute(\n"
        '            "SELECT role, content FROM chat_history WHERE chat_id=?"\n'
        '            " ORDER BY ts DESC LIMIT ?", (chat_id, HISTORY_TURNS),\n'
        "        ).fetchall()\n"
        '    return [{"role": r, "content": c} for r, c in reversed(rows)]\n'
        "\n"
        "\n"
        "def _remember(chat_id: str, role: str, content: str) -> None:\n"
        "    with _connect() as conn:\n"
        "        conn.execute(\n"
        '            "INSERT INTO chat_history (chat_id, role, content)"\n'
        '            " VALUES (?, ?, ?)", (chat_id, role, content),\n'
        "        )\n"
        "\n"
        "\n"
        "# --- the bot ------------------------------------------------------\n"
        "\n"
        "SPEC = _build_spec()\n"
        "\n"
        "\n"
        "def _answer(chat_id: str, text: str) -> str:\n"
        '    """One interactive turn, history-threaded. Sync — called in a\n'
        "    thread so the event loop stays responsive.\"\"\"\n"
        "    result = run_interactive(\n"
        "        SPEC, text, tool_runner=_tool_runner, history=_history(chat_id),\n"
        "    )\n"
        '    _remember(chat_id, "user", text)\n'
        '    _remember(chat_id, "assistant", result.output_text)\n'
        "    if result.error:\n"
        '        return f"(error: {result.error})"\n'
        "    return result.output_text or \"(no reply)\"\n"
        "\n"
        "\n"
        "async def _on_message(update: Update, ctx: ContextTypes.DEFAULT_TYPE) -> None:\n"
        "    if update.message is None or not update.message.text:\n"
        "        return\n"
        "    chat_id = str(update.effective_chat.id)\n"
        "    reply = await asyncio.to_thread(_answer, chat_id, update.message.text)\n"
        "    await update.message.reply_text(reply[:4000])\n"
        "\n"
        "\n"
        "def main() -> None:\n"
        '    token = os.environ.get("TELEGRAM_BOT_TOKEN")\n'
        "    if not token:\n"
        '        raise SystemExit("TELEGRAM_BOT_TOKEN is not set (see .env.example)")\n'
        "    app = Application.builder().token(token).build()\n"
        "    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, _on_message))\n"
        '    print(json.dumps({"status": "polling", "db": str(DB_PATH)}))\n'
        "    app.run_polling()\n"
        "\n"
        "\n"
        'if __name__ == "__main__":\n'
        "    main()\n"
    )
